### PR TITLE
Email and EmailOrUsername forms were added

### PR DESCRIPTION
**Pull request by 777RND777**
Duplicate forms were removed.
Email form was used in forms that are based on email.
EmailOrUsername form was used in forms that are based on email or username.

### CODE REVIEW

**Comment by egorsmkv** [comment]
Hello.

Are you still working on this pull request or you have finished it?

**Comment by 777RND777** [comment]
Yep, I've finished it. Just a small addition. If you don't like it or
anything like this, that's fine :)
If you reject my pull request, I would be really thankful, of you explained
me what is wrong in it.

**Comment by egorsmkv** [comment]
I'll look into your changes later and tell you my thoughts. Thanks for your attention to the project.

**Comment by egorsmkv** [comment]
Just reviewed your pull request and tested on my local machine. All look fine.

Thanks for this optimisation.

**Pull request merged**
